# Generated by Django 5.2.17 on 2026-09-19 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=50)),
                ('service_type', models.CharField(default='Custom Tattoo Art', max_length=150)),
                ('placement', models.CharField(default='Forearm', max_length=100)),
                ('size_estimate', models.CharField(default='Medium (4-6 inches)', max_length=100)),
                ('budget_range', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_dates', models.CharField(blank=True, default='', max_length=200)),
                ('tattoo_description', models.TextField()),
                ('reference_photo', models.ImageField(blank=True, null=True, upload_to='booking_references/')),
                ('reference_photo_url', models.URLField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('artist_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking Request',
                'verbose_name_plural': 'Booking Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=150)),
                ('client_location', models.CharField(default='Gujarat, India', max_length=150)),
                ('tattoo_piece', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('healed_time', models.CharField(default='Healed 6 Months', max_length=100)),
                ('service_type', models.CharField(default='Studio Visit', max_length=100)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Review',
                'verbose_name_plural': 'Customer Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
