# Generated by Django 5.2.17 on 2026-09-18 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSyncRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_media_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('SOURCE_UNAVAILABLE', 'Source Unavailable')], default='SUCCESS', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instagram Sync Record',
                'verbose_name_plural': 'Instagram Sync Records',
                'ordering': ['-last_synced_at'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Body Placement',
                'verbose_name_plural': 'Body Placements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncBatchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_processed', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial with Errors')], default='IN_PROGRESS', max_length=30)),
                ('log_details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Sync Batch Log',
                'verbose_name_plural': 'Sync Batch Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TattooStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tattoo Style',
                'verbose_name_plural': 'Tattoo Styles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_media_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('instagram_permalink', models.URLField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Single Image'), ('VIDEO', 'Video / Reel'), ('CAROUSEL_ALBUM', 'Carousel Album')], default='IMAGE', max_length=30)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('color_type', models.CharField(choices=[('Black & Grey', 'Black & Grey'), ('Color', 'Color'), ('Single Needle', 'Single Needle'), ('Mixed', 'Mixed')], default='Black & Grey', max_length=50)),
                ('session_hours', models.FloatField(blank=True, null=True)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('HIDDEN', 'Hidden'), ('FAILED', 'Failed Sync'), ('SOURCE_UNAVAILABLE', 'Source Unavailable')], db_index=True, default='PUBLISHED', max_length=30)),
                ('ai_suggested_style', models.CharField(blank=True, max_length=100)),
                ('ai_suggested_placement', models.CharField(blank=True, max_length=100)),
                ('ai_suggested_tags', models.CharField(blank=True, max_length=255)),
                ('ai_confidence_score', models.FloatField(default=0.0)),
                ('like_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='portfolio.placement')),
                ('tags', models.ManyToManyField(blank=True, related_name='portfolio_items', to='portfolio.tag')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='portfolio.tattoostyle')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(default='IMAGE', max_length=20)),
                ('source_url', models.TextField()),
                ('storage_url', models.TextField(blank=True)),
                ('thumbnail_url', models.TextField(blank=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='portfolio.portfolioitem')),
            ],
            options={
                'verbose_name': 'Portfolio Media',
                'verbose_name_plural': 'Portfolio Media Items',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['status', 'published'], name='portfolio_p_status_4d776f_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['featured', 'published'], name='portfolio_p_feature_d17e29_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['published_at'], name='portfolio_p_publish_310e15_idx'),
        ),
    ]
