import type {
  ArtistProfile,
  PortfolioItem,
  VideoReel,
  ServiceOffering,
  ReviewItem,
  BookingRequest,
  CalendarEvent,
  CustomerRecord,
} from "@/types";

// ── SIZES & TIME_SLOTS & STYLES ──
export const SIZES = [
  { value: "small", label: "Small (under 3 inches / 7cm)" },
  { value: "medium", label: "Medium (3–6 inches / 7–15cm)" },
  { value: "large", label: "Large (6–10 inches / 15–25cm)" },
  { value: "extra_large", label: "Extra Large / Half Sleeve (10+ inches)" },
  { value: "full_day", label: "Full Day Session / Full Sleeve / Back Piece" },
];

export const TIME_SLOTS = [
  "10:00",
  "11:00",
  "12:30",
  "14:00",
  "15:30",
  "16:30",
];

export const TATTOO_STYLES = [
  "Fine Line",
  "Blackwork",
  "Realism",
  "Minimalist",
  "Traditional",
  "Custom",
];

export const STATUS_CONFIG: Record<string, { label: string; color: string }> = {
  pending: { label: "Pending Review", color: "text-amber-400 bg-amber-500/10 border-amber-500/20" },
  accepted: { label: "Accepted", color: "text-blue-400 bg-blue-500/10 border-blue-500/20" },
  deposit_required: { label: "Deposit Required", color: "text-amber-300 bg-amber-500/15 border-amber-500/30" },
  confirmed: { label: "Confirmed", color: "text-emerald-400 bg-emerald-500/10 border-emerald-500/20" },
  completed: { label: "Completed", color: "text-purple-400 bg-purple-500/10 border-purple-500/20" },
  rejected: { label: "Declined", color: "text-red-400 bg-red-500/10 border-red-500/20" },
  cancelled: { label: "Cancelled", color: "text-ink-400 bg-white/5 border-white/10" },
};

// ── Master Artist Profile ──
export const ARTIST_PROFILE: ArtistProfile = {
  id: "jainik-patel",
  full_name: "Jainik Patel",
  title: "Professional Tattoo Artist & Studio Owner",
  bio: "With over 10+ years of dedicated tattoo mastery and more than 7,000+ collectors inked, Jainik Patel is the founder and lead artist of Tattoo Iconic. Based in At-Post Bhadam, Taluka- Rajpipla, District- Narmada, Jainik offers exclusive private studio sessions as well as luxury at-your-home mobile service across Gujarat.",
  experience_years: 10,
  studio_name: "Tattoo Iconic",
  location_summary: "At-Post Bhadam, Taluka- Rajpipla, District- Narmada, Gujarat (Studio & Home Service)",
  specialties: [
    "Fine Line & Micro-Realism",
    "Dark Realism & Surrealism",
    "Illustrative Blackwork",
    "Minimalist Geometric",
    "Custom Cover-ups",
  ],
  awards: [
    "10+ Years of Professional Tattoo Mastery",
    "7,000+ Happy Collectors Inked Across India",
    "Premier Studio & Luxury Mobile Home Inking Specialist",
  ],
  instagram_handle: "tatoo.iconic",
  phone: "+91 8238767100",
  whatsapp_number: "+918238767100",
  email: "Jainik.patel.33@gmail.com",
  profile_image: "/images/tattoo-iconic-logo.png",
  studio_image: "https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?auto=format&fit=crop&w=1200&q=80",
  hourly_rate: 1500,
  minimum_deposit: 1000,
  is_accepting_bookings: true,
  offers_home_service: true,
  home_service_radius: "Rajpipla, Narmada, Bharuch, Vadodara, Surat & surrounding areas (Travel fee applies based on distance)",
  booking_lead_days: 2,
  stats: {
    pieces_completed: "7,000+",
    experience: "10+ Years",
    rating: 5.0,
    reviews_count: "450+",
    healed_rate: "99.9%",
  },
};

export const MASTER_ARTIST = ARTIST_PROFILE;

// ── Tattoo Styles Catalog ──
export const TATTOO_STYLES_CATALOG = [
  {
    id: "fine-line",
    name: "Fine Line",
    short_desc: "Single-needle precision, intricate botanical florals, delicate script, and micro-geometry.",
    image: "/images/tattoos/lotus-mandala-tattoo.jpg",
    popular_placements: "Forearm, Spine, Ribs, Collarbone",
  },
  {
    id: "blackwork",
    name: "Blackwork",
    short_desc: "Bold high-contrast ink, solid blacks, stipple shading, and dark atmospheric themes.",
    image: "/images/tattoos/serpent-peony-tattoo.jpg",
    popular_placements: "Arm Sleeve, Calf, Upper Back",
  },
  {
    id: "realism",
    name: "Realism",
    short_desc: "Photorealistic portraits, classical sculptures, animal textures, and smooth gradient shading.",
    image: "/images/tattoos/lion-king-tattoo.jpg",
    popular_placements: "Bicep, Chest, Thigh",
  },
  {
    id: "minimalist",
    name: "Minimalist",
    short_desc: "Clean silhouettes, subtle micro-tattoos, symbolic linework, and understated elegance.",
    image: "/images/tattoos/maa-calligraphy-tattoo.jpg",
    popular_placements: "Wrist, Ankle, Behind Ear, Finger",
  },
  {
    id: "traditional",
    name: "Traditional & Neo-Trad",
    short_desc: "Timeless iconography, bold outlines, saturated gradients, and modern mythological motifs.",
    image: "/images/tattoos/shivaji-maharaj-tattoo.jpg",
    popular_placements: "Shoulder, Thigh, Forearm",
  },
  {
    id: "custom",
    name: "Custom Designs",
    short_desc: "100% original conceptual compositions tailored exclusively to your personal story and anatomy.",
    image: "/images/tattoos/rudraksha-trishul-tattoo.jpg",
    popular_placements: "Full Back, Torso, Sleeve Projects",
  },
];

// ── Curated Portfolio (Tattoo Iconic / Jainik Patel Master Collection) ──
export const PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: "piece-1",
    title: "Lord Hanuman Ji — Ornate Mukut & Calligraphy",
    description: "Intricate spiritual realism portrait of Lord Hanuman with detailed ornamental crown (Mukut), sacred saffron tilak, and bold Hindi calligraphy on the forearm.",
    image: "/images/tattoos/hanuman-tattoo.jpg",
    healed_image: "/images/tattoos/hanuman-tattoo.jpg",
    video_url: "https://assets.mixkit.co/videos/preview/mixkit-tattoo-artist-working-on-a-customers-arm-43187-large.mp4",
    style_tags: ["Spiritual", "Realism", "Fine Line", "Script"],
    primary_style: "Spiritual",
    placement: "Forearm",
    size: "7–9 inches",
    color_type: "Black & Grey",
    session_hours: 6,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2024-03-12",
    client_story: "Custom devotional inking representing strength, unwavering devotion, and divine protection.",
  },
  {
    id: "piece-2",
    title: "Lord Shiva Cosmic Trishul & Damru Flow",
    description: "Spiritual micro-stipple shading depicting Mahadev with celestial Trishul, crescent moon, and sacred mandala geometry.",
    image: "/images/tattoos/shiva-trishul-tattoo.jpg",
    healed_image: "/images/tattoos/shiva-trishul-tattoo.jpg",
    style_tags: ["Spiritual", "Fine Line", "Custom"],
    primary_style: "Spiritual",
    placement: "Forearm / Upper Arm",
    size: "8–10 inches",
    color_type: "Black & Grey",
    session_hours: 6.5,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2024-02-28",
    client_story: "Dedicated to divine peace and cosmic energy, contoured along forearm muscle anatomy.",
  },
  {
    id: "piece-3",
    title: "Royal Lion & Crown Dark Realism Sleeve",
    description: "Photorealistic lion portrait with piercing gaze, vintage royal crown engravings, and micro-whisker highlights.",
    image: "/images/tattoos/lion-king-tattoo.jpg",
    healed_image: "/images/tattoos/lion-king-tattoo.jpg",
    style_tags: ["Realism", "Blackwork"],
    primary_style: "Realism",
    placement: "Arm / Bicep",
    size: "10–12 inches",
    color_type: "Black & Grey",
    session_hours: 8,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2024-02-15",
    client_story: "Symbol of leadership, inner courage, and regal heritage.",
  },
  {
    id: "piece-4",
    title: "Sacred Lotus Mandala & Micro-Geometry",
    description: "Ultra-crisp geometric symmetry and delicate blooming lotus petals crafted with single-needle precision.",
    image: "/images/tattoos/lotus-mandala-tattoo.jpg",
    healed_image: "/images/tattoos/lotus-mandala-tattoo.jpg",
    style_tags: ["Fine Line", "Minimalist", "Geometric"],
    primary_style: "Fine Line",
    placement: "Shoulder / Arm",
    size: "6 inches",
    color_type: "Black & Grey",
    session_hours: 4.5,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2024-01-20",
    client_story: "Spiritual purity, rebirth, and sacred geometric alignment.",
  },
  {
    id: "piece-5",
    title: "Maa Devotional Calligraphy & Sacred Lotus",
    description: "Single-needle Devanagari Sanskrit calligraphy with customized lettering integrated into ECG heartbeat and floating micro-lotus petals.",
    image: "/images/tattoos/maa-calligraphy-tattoo.jpg",
    healed_image: "/images/tattoos/maa-calligraphy-tattoo.jpg",
    style_tags: ["Script", "Fine Line", "Spiritual"],
    primary_style: "Fine Line",
    placement: "Wrist / Forearm",
    size: "4–5 inches",
    color_type: "Single Needle",
    session_hours: 3.5,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2024-01-08",
    client_story: "Heartfelt tribute honoring mother's endless blessings.",
  },
  {
    id: "piece-6",
    title: "Shree Ganesha Sacred Line Art & Tilak",
    description: "Devotional minimalist line art of Lord Ganesha with holy saffron tilak, modak flourish, and auspicious blessing mudra.",
    image: "/images/tattoos/ganesha-tattoo.jpg",
    healed_image: "/images/tattoos/ganesha-tattoo.jpg",
    style_tags: ["Spiritual", "Fine Line", "Minimalist"],
    primary_style: "Spiritual",
    placement: "Forearm / Wrist",
    size: "5–6 inches",
    color_type: "Black & Grey",
    session_hours: 4,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2023-12-22",
    client_story: "Invoking auspicious beginnings and remover of all obstacles.",
  },
  {
    id: "piece-7",
    title: "Chhatrapati Shivaji Maharaj Imperial Portrait",
    description: "Detailed historical realism tribute featuring the Great Maratha King with royal turban (pagadi), sharp mustache, and ornate sword hilt.",
    image: "/images/tattoos/shivaji-maharaj-tattoo.jpg",
    healed_image: "/images/tattoos/shivaji-maharaj-tattoo.jpg",
    style_tags: ["Realism", "Spiritual", "Custom"],
    primary_style: "Realism",
    placement: "Chest / Shoulder",
    size: "8–10 inches",
    color_type: "Black & Grey",
    session_hours: 8.5,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2023-12-05",
    client_story: "Pride in Maratha legacy and fearless warrior spirit.",
  },
  {
    id: "piece-8",
    title: "Lord Shiva Trishul with Rudraksha Mala & Damru",
    description: "Spiritual realism featuring sacred Lord Shiva Trishul wrapped in textured Rudraksha bead mala necklace and holy Damru drum.",
    image: "/images/tattoos/rudraksha-trishul-tattoo.jpg",
    healed_image: "/images/tattoos/rudraksha-trishul-tattoo.jpg",
    style_tags: ["Spiritual", "Realism", "Custom"],
    primary_style: "Spiritual",
    placement: "Forearm",
    size: "8–9 inches",
    color_type: "Black & Grey",
    session_hours: 5.5,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2023-11-18",
    client_story: "Protection and inner awakening through Mahadev's divine grace.",
  },
  {
    id: "piece-9",
    title: "Dark Realism Cobra Serpent & Blooming Peonies",
    description: "High-contrast illustrative blackwork serpent coiled gracefully through large blossoming botanical peony flowers with dark stipple shading.",
    image: "/images/tattoos/serpent-peony-tattoo.jpg",
    healed_image: "/images/tattoos/serpent-peony-tattoo.jpg",
    style_tags: ["Blackwork", "Realism", "Botanical"],
    primary_style: "Blackwork",
    placement: "Forearm",
    size: "8–9 inches",
    color_type: "Black & Grey",
    session_hours: 6,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2023-10-30",
    client_story: "Transformation, rebirth, and duality of beauty and danger.",
  },
  {
    id: "piece-10",
    title: "Lord Buddha Meditative Nirvana & Sacred Lotus",
    description: "Serene meditative Lord Buddha face portrait in soft smoky black and grey shading with blooming sacred lotus blossom and Bodhi tree leaves.",
    image: "/images/tattoos/buddha-nirvana-tattoo.jpg",
    healed_image: "/images/tattoos/buddha-nirvana-tattoo.jpg",
    style_tags: ["Realism", "Spiritual", "Fine Line"],
    primary_style: "Spiritual",
    placement: "Forearm / Bicep",
    size: "6–8 inches",
    color_type: "Black & Grey",
    session_hours: 7,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2023-10-12",
    client_story: "Inner peace, mindfulness, and spiritual enlightenment.",
  },
  {
    id: "piece-11",
    title: "Geometric Wolf & Howling Moon Forest Realism",
    description: "Geometric polygon wolf head seamlessly transitioning into realistic howling wolf portrait against full moon and pine forest silhouettes.",
    image: "/images/tattoos/wolf-forest-tattoo.jpg",
    healed_image: "/images/tattoos/wolf-forest-tattoo.jpg",
    style_tags: ["Geometric", "Realism", "Blackwork"],
    primary_style: "Geometric",
    placement: "Forearm",
    size: "7–8 inches",
    color_type: "Black & Grey",
    session_hours: 6,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2023-09-25",
    client_story: "Loyalty to the pack, instinct, and harmony with wilderness.",
  },
  {
    id: "piece-12",
    title: "Radha Krishna Divine Flute & Morpankh",
    description: "Fine-line devotional tattoo featuring Lord Krishna's sacred Bansuri flute with detailed peacock feather (Mor Pankh) and glowing spiritual flourishes.",
    image: "/images/tattoos/radha-krishna-tattoo.jpg",
    healed_image: "/images/tattoos/radha-krishna-tattoo.jpg",
    style_tags: ["Spiritual", "Fine Line", "Custom"],
    primary_style: "Spiritual",
    placement: "Forearm / Wrist",
    size: "6–7 inches",
    color_type: "Single Needle",
    session_hours: 4.5,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2023-08-30",
    client_story: "Pure unconditional divine love and celestial melody.",
  },
  {
    id: "piece-13",
    title: "Vintage Pocket Watch, Broken Glass & Dark Rose Realism",
    description: "Intricate vintage Roman numeral pocket watch with broken glass dial effect and velvety realistic dark rose flower petals.",
    image: "/images/tattoos/rose-clock-tattoo.jpg",
    healed_image: "/images/tattoos/rose-clock-tattoo.jpg",
    style_tags: ["Realism", "Blackwork"],
    primary_style: "Realism",
    placement: "Forearm / Sleeve",
    size: "8–10 inches",
    color_type: "Black & Grey",
    session_hours: 7.5,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2023-08-05",
    client_story: "Cherishing every fleeting moment and enduring beauty through time.",
  },
  {
    id: "piece-14",
    title: "Mahamrityunjaya Mantra Forearm Sacred Wrap",
    description: "Devotional Devanagari Sanskrit mantra calligraphy seamlessly contoured around the forearm with sacred Om accents.",
    image: "/images/tattoos/shiva-trishul-tattoo.jpg",
    healed_image: "/images/tattoos/shiva-trishul-tattoo.jpg",
    style_tags: ["Script", "Spiritual", "Custom"],
    primary_style: "Script",
    placement: "Forearm Band",
    size: "Band (Wrap)",
    color_type: "Single Needle",
    session_hours: 5,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2023-07-28",
    client_story: "Maha Mrityunjaya mantra for longevity and liberation.",
  },
  {
    id: "piece-15",
    title: "Imperial Maratha Royal Shield & Trishul",
    description: "Historical homage celebrating warrior valor with royal emblem and intricate ornamental filigree.",
    image: "/images/tattoos/shivaji-maharaj-tattoo.jpg",
    healed_image: "/images/tattoos/shivaji-maharaj-tattoo.jpg",
    style_tags: ["Realism", "Custom", "Blackwork"],
    primary_style: "Realism",
    placement: "Shoulder / Bicep",
    size: "8 inches",
    color_type: "Black & Grey",
    session_hours: 7.5,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2023-07-14",
    client_story: "Honoring valor, integrity, and ancestral roots.",
  },
  {
    id: "piece-16",
    title: "Sacred Om & Cosmic Trishul Stipple Flow",
    description: "Dotwork mandala aura radiating around holy Trishul with Damru and sacred Sanskrit script.",
    image: "/images/tattoos/rudraksha-trishul-tattoo.jpg",
    healed_image: "/images/tattoos/rudraksha-trishul-tattoo.jpg",
    style_tags: ["Spiritual", "Geometric", "Fine Line"],
    primary_style: "Spiritual",
    placement: "Forearm",
    size: "7–8 inches",
    color_type: "Black & Grey",
    session_hours: 5,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2023-06-20",
    client_story: "Spiritual alignment and protective energy.",
  },
  {
    id: "piece-17",
    title: "Goddess Durga & Sacred Lotus Mandala",
    description: "Devotional fine-line composition celebrating Shakti with ornate crown and blooming geometric petals.",
    image: "/images/tattoos/lotus-mandala-tattoo.jpg",
    healed_image: "/images/tattoos/lotus-mandala-tattoo.jpg",
    style_tags: ["Spiritual", "Fine Line", "Geometric"],
    primary_style: "Fine Line",
    placement: "Back / Shoulder Blade",
    size: "8–10 inches",
    color_type: "Black & Grey",
    session_hours: 6.5,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2023-05-18",
    client_story: "Divine feminine strength and serenity.",
  },
  {
    id: "piece-18",
    title: "Devotional Lord Hanuman Face & Saffron Chintamani",
    description: "High-definition portrait of Bajrangbali with intense devotion and razor-sharp linework highlights.",
    image: "/images/tattoos/hanuman-tattoo.jpg",
    healed_image: "/images/tattoos/hanuman-tattoo.jpg",
    style_tags: ["Spiritual", "Realism", "Custom"],
    primary_style: "Spiritual",
    placement: "Forearm / Bicep",
    size: "8 inches",
    color_type: "Black & Grey",
    session_hours: 6.5,
    is_featured: true,
    is_published: true,
    artist_name: "Jainik Patel",
    artist_id: "jainik-patel",
    created_at: "2023-04-10",
    client_story: "Eternal devotion, humility, and invincible courage.",
  },
];

export const CURATED_PORTFOLIO = PORTFOLIO_ITEMS;

// ── Video Reels ──
export const VIDEO_REELS: VideoReel[] = [
  {
    id: "reel-1",
    title: "Single-Needle Botanical Process on Forearm",
    thumbnail: "https://images.unsplash.com/photo-1560707303-4e980ce876ad?auto=format&fit=crop&w=600&q=80",
    video_url: "https://assets.mixkit.co/videos/preview/mixkit-tattoo-artist-working-on-a-customers-arm-43187-large.mp4",
    duration: "0:45",
    views: "128k",
    style: "Fine Line",
    description: "Watch the meticulous stipple layering and feather-light touch during this 5-hour custom inking session.",
  },
  {
    id: "reel-2",
    title: "Home Service VIP Setup & Client Inking",
    thumbnail: "https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?auto=format&fit=crop&w=600&q=80",
    video_url: "https://assets.mixkit.co/videos/preview/mixkit-tattoo-artist-working-on-a-customers-arm-43187-large.mp4",
    duration: "0:58",
    views: "94k",
    style: "Home Service",
    description: "Complete walkthrough of sterile mobile station setup, skin sanitization, and seamless in-home session.",
  },
  {
    id: "reel-3",
    title: "Chiaroscuro Shading Technique Close-up",
    thumbnail: "https://images.unsplash.com/photo-1562962230-16e4623d36e6?auto=format&fit=crop&w=600&q=80",
    video_url: "https://assets.mixkit.co/videos/preview/mixkit-tattoo-artist-working-on-a-customers-arm-43187-large.mp4",
    duration: "0:38",
    views: "215k",
    style: "Realism",
    description: "Macro needle view showing ultra-smooth tonal transitions without overworking the skin.",
  },
];

// ── Service Catalog (2 Core Exclusive Offerings) ──
export const SERVICES_CATALOG: ServiceOffering[] = [
  {
    id: "srv-studio",
    slug: "studio-visit",
    title: "Studio Visit (Customer Visits Artist's House)",
    short_desc: "Visit Jainik's private studio suite in Bhadam, Rajpipla for an exclusive, tranquil 1-on-1 inking session.",
    full_desc: "Experience your session in a dedicated, private studio suite in Bhadam, Rajpipla. Enjoy complete 1-on-1 focus with zero studio distractions, ergonomic memory-foam seating, and clinical sterilization with medical vacuum autoclaves.",
    suitable_for: ["Private 1-on-1 sessions", "Detailed custom tattoos", "All styles and placements"],
    process_steps: ["1-on-1 Concept Discussion", "Digital Stencil & Sizing Check", "Sterile Cartridge Setup", "Master Inking Session & Medical Second-Skin Wrap"],
    estimated_duration: "Custom per piece",
    price_model: "Hourly",
    hourly_rate: 1500,
    starting_price: 1000,
    service_type: "studio",
    image: "https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?auto=format&fit=crop&w=800&q=80",
    icon: "MapPin",
    features: [
      "Private studio in Bhadam, Taluka- Rajpipla, Narmada",
      "Hospital-grade Class-B vacuum autoclave sterilization",
      "Single-use surgical cartridges opened in front of you",
      "Ergonomic seating, peaceful acoustics & zero distractions",
      "Medical second-skin dressing & full healing care kit included",
    ],
  },
  {
    id: "srv-home",
    slug: "home-service",
    title: "Luxury Home Service (Artist Visits Customer's House)",
    short_desc: "Jainik brings the complete sterile mobile tattoo studio directly to your private residence across Gujarat.",
    full_desc: "For clients seeking maximum convenience, privacy, and luxury, Jainik travels with a complete portable sterile workstation directly to your home. Available across Rajpipla, Narmada, Bharuch, Vadodara, Surat, and surrounding regions.",
    suitable_for: ["In-home comfort & zero travel", "VIP & high-profile clients wanting privacy", "Family & custom home sessions"],
    process_steps: ["Concept Consultation & Location Confirm", "Sterile Mobile Workstation Setup at Your Home", "In-Home Master Tattoo Session", "Medical Second-Skin Application & Aftercare Kit"],
    estimated_duration: "Custom per piece",
    price_model: "Fixed Starting",
    starting_price: 1500,
    service_type: "home",
    image: "https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?auto=format&fit=crop&w=800&q=80",
    icon: "Home",
    features: [
      "Jainik travels directly to your doorstep",
      "Complete mobile sanitized workstation & sterile drape setup",
      "Zero travel stress — relax comfortably in your own home",
      "Strict client confidentiality & VIP privacy",
      "Medical second-skin dressing & 21-day WhatsApp healing support",
    ],
  },
];

// ── Verified Customer Reviews ──
export const CUSTOMER_REVIEWS: ReviewItem[] = [
  {
    id: "rev-1",
    client_name: "Aarav Patel",
    client_location: "Vadodara, Gujarat",
    rating: 5,
    service_type: "Studio Visit",
    tattoo_piece: "Lord Hanuman Ji Spiritual Forearm",
    style: "Spiritual & Realism",
    healed_time: "Healed 8 months",
    comment:
      "Jainik's attention to anatomical placement and sacred calligraphy is extraordinary. The studio in Bhadam is serene, sterile, and unhurried. 8 months later, the healed fine lines are as crisp as day one.",
    healed_photo: "/images/tattoos/hanuman-tattoo.jpg",
    created_at: "2024-02-14",
    is_verified: true,
  },
  {
    id: "rev-2",
    client_name: "Sneha Desai",
    client_location: "Rajpipla, Narmada",
    rating: 5,
    service_type: "Home Service",
    tattoo_piece: "Sacred Lotus Mandala & Geometry",
    style: "Fine Line",
    healed_time: "Healed 6 months",
    comment:
      "Booking Jainik for a home service appointment was the best decision. He brought hospital-grade sterilization equipment, set up quietly, and made the session completely relaxing in my own home.",
    healed_photo: "/images/tattoos/lotus-mandala-tattoo.jpg",
    created_at: "2024-01-20",
    is_verified: true,
  },
  {
    id: "rev-3",
    client_name: "Hardik Shah",
    client_location: "Bharuch, Gujarat",
    rating: 5,
    service_type: "Studio Visit",
    tattoo_piece: "Lord Shiva Cosmic Trishul & Damru",
    style: "Spiritual Realism",
    healed_time: "Healed 1 year",
    comment:
      "True master of micro-shading. Other artists told me the micro-dotwork would blur together, but Jainik's technique preserved every single detail. Worth every rupee.",
    healed_photo: "/images/tattoos/shiva-trishul-tattoo.jpg",
    created_at: "2023-11-12",
    is_verified: true,
  },
  {
    id: "rev-4",
    client_name: "Priya Sharma",
    client_location: "Surat, Gujarat",
    rating: 5,
    service_type: "Custom Project",
    tattoo_piece: "Royal Lion King Sleeve",
    style: "Dark Realism",
    healed_time: "Healed 4 months",
    comment:
      "Jainik is a true master artist. He spent 45 minutes making sure the stencil was placed at the millimeter-exact anatomical flow. The healing process with his second-skin wrap was flawless.",
    healed_photo: "/images/tattoos/lion-king-tattoo.jpg",
    created_at: "2024-03-01",
    is_verified: true,
  },
];

// ── Instagram Grid Highlights ──
export const INSTAGRAM_POSTS = [
  {
    id: "ig-1",
    image: "https://images.unsplash.com/photo-1560707303-4e980ce876ad?auto=format&fit=crop&w=600&q=80",
    likes: "2.4k",
    comments: "84",
    caption: "Dark realism serpent in progress. Fresh inking on forearm. #JainikPatelTattoos #DarkRealism",
  },
  {
    id: "ig-2",
    image: "https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?auto=format&fit=crop&w=600&q=80",
    likes: "3.8k",
    comments: "142",
    caption: "Single needle spine cascade healed 6 months. Clean, crisp, eternal. #FineLineTattoo",
  },
  {
    id: "ig-3",
    image: "https://images.unsplash.com/photo-1562962230-16e4623d36e6?auto=format&fit=crop&w=600&q=80",
    likes: "1.9k",
    comments: "67",
    caption: "Micro-portraiture Roman bust. Soft needle stippling. #TattooArt #RealismTattoo",
  },
  {
    id: "ig-4",
    image: "https://images.unsplash.com/photo-1568515045052-f9a854d70bfd?auto=format&fit=crop&w=600&q=80",
    likes: "2.1k",
    comments: "53",
    caption: "Sacred geometry sternum piece. Pure symmetry. #MinimalistTattoo",
  },
  {
    id: "ig-5",
    image: "https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?auto=format&fit=crop&w=600&q=80",
    likes: "4.2k",
    comments: "190",
    caption: "Home service VIP session in private residence. Sterile and serene. #MobileTattoo #LuxuryTattoo",
  },
  {
    id: "ig-6",
    image: "https://images.unsplash.com/photo-1542385151-efd9000785a0?auto=format&fit=crop&w=600&q=80",
    likes: "1.7k",
    comments: "49",
    caption: "Botanical heart study. Custom designed for Priya. #CustomTattoo",
  },
];

// ── FAQs ──
export const STUDIO_FAQS = [
  {
    question: "How does the booking and consultation process work?",
    answer:
      "You start by submitting our 7-step booking request with your tattoo concept, size, placement, and reference images. Jainik reviews every request personally. Once accepted, you receive a confirmation message and deposit details to secure your date.",
  },
  {
    question: "How does the Home Service option work?",
    answer:
      "For clients who prefer the privacy and convenience of their home, Jainik brings a full mobile studio with medical autoclave-sterilized equipment, disposable surgical supplies, ergonomic lighting, and sanitizing barriers. We service Rajpipla, Narmada District, and surrounding regions (travel fee calculated based on distance).",
  },
  {
    question: "What is your deposit policy?",
    answer:
      "A non-refundable deposit is required to secure your appointment and begin design drafting. The deposit is fully deducted from your final balance on tattoo day.",
  },
  {
    question: "Where is the private studio located?",
    answer:
      "Jainik operates from a private studio atelier located at At-Post Bhadam, Taluka- Rajpipla, District- Narmada, Gujarat. To maintain an exclusive, peaceful environment with zero foot traffic, exact landmark directions and parking instructions are provided upon booking approval.",
  },
  {
    question: "What pigments and needles do you use?",
    answer:
      "Only 100% REACH-compliant, organic vegan pigments free from heavy metals, and single-use EO gas-sterilized surgical steel cartridges opened in front of you.",
  },
  {
    question: "How should I prepare for my tattoo appointment?",
    answer:
      "Get a good night's sleep, eat a substantial meal 1–2 hours before your appointment, and stay hydrated. Avoid alcohol for 24 hours prior. Wear comfortable loose clothing that easily exposes the tattoo placement area.",
  },
];

// ── Global Nav Links ──
export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/portfolio", label: "Portfolio" },
  { href: "/services", label: "Services" },
  { href: "/reviews", label: "Reviews" },
  { href: "/contact", label: "Contact" },
];

// ── Dashboard Links ──
export const DASHBOARD_LINKS = [
  { href: "/dashboard", label: "Overview", icon: "LayoutDashboard" },
  { href: "/dashboard/bookings", label: "Bookings", icon: "CalendarCheck" },
  { href: "/dashboard/calendar", label: "Calendar", icon: "Calendar" },
  { href: "/dashboard/portfolio", label: "Portfolio Manager", icon: "Image" },
  { href: "/dashboard/customers", label: "Customers", icon: "Users" },
  { href: "/dashboard/settings", label: "Settings", icon: "Settings" },
];

// ── Mock Initial Bookings for Dashboard ──
export const INITIAL_MOCK_BOOKINGS: BookingRequest[] = [
  {
    id: "bk-101",
    customer_name: "Sophie Chen",
    customer_email: "sophie.chen@gmail.com",
    customer_phone: "+44 7911 123456",
    whatsapp_preferred: true,
    tattoo_description: "Delicate fine-line lotus flower with subtle geometric accents down the spine.",
    tattoo_style: "Fine Line",
    placement: "Spine / Upper Back",
    approx_size: "6 inches",
    color_preference: "Black & Grey",
    reference_images: ["https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?auto=format&fit=crop&w=600&q=80"],
    service_type: "studio_visit",
    preferred_date: "2026-09-12",
    preferred_time: "11:00",
    status: "pending",
    estimated_price: 320,
    deposit_amount: 80,
    deposit_paid: false,
    created_at: "2026-09-01T08:30:00Z",
    updated_at: "2026-09-01T08:30:00Z",
  },
  {
    id: "bk-102",
    customer_name: "David Miller",
    customer_email: "david.m@outlook.com",
    customer_phone: "+44 7822 654321",
    tattoo_description: "Dark realism skull and watch pocket composition wrapping the outer bicep.",
    tattoo_style: "Realism",
    placement: "Bicep",
    approx_size: "Large Scale (8 inches)",
    color_preference: "Black & Grey",
    reference_images: ["https://images.unsplash.com/photo-1562962230-16e4623d36e6?auto=format&fit=crop&w=600&q=80"],
    service_type: "home_service",
    home_address: {
      street: "Main Bazaar Road",
      city: "Rajpipla",
      postcode: "393145",
      notes: "Private residence, parking available.",
    },
    preferred_date: "2026-09-15",
    preferred_time: "13:00",
    status: "deposit_required",
    estimated_price: 650,
    deposit_amount: 150,
    deposit_paid: false,
    created_at: "2026-08-30T14:15:00Z",
    updated_at: "2026-08-31T10:00:00Z",
  },
  {
    id: "bk-103",
    customer_name: "Elena Vance",
    customer_email: "elena.v@artstudio.co.uk",
    customer_phone: "+91 9822334455",
    tattoo_description: "Micro-botanical sprigs of lavender and wild thyme around wrist.",
    tattoo_style: "Fine Line",
    placement: "Wrist / Forearm",
    approx_size: "3 inches",
    color_preference: "Black & Grey",
    reference_images: [],
    service_type: "studio_visit",
    preferred_date: "2026-09-08",
    preferred_time: "10:30",
    status: "confirmed",
    estimated_price: 180,
    deposit_amount: 80,
    deposit_paid: true,
    created_at: "2026-08-25T11:00:00Z",
    updated_at: "2026-08-26T16:00:00Z",
  },
  {
    id: "bk-104",
    customer_name: "Marcus Aurelius Reed",
    customer_email: "marcus.reed@luxury.com",
    customer_phone: "+91 9811223344",
    tattoo_description: "Full neo-Japanese sleeve with dragon scales, waves, and cherry blossoms.",
    tattoo_style: "Traditional",
    placement: "Full Sleeve",
    approx_size: "Full Project",
    color_preference: "Black & Grey",
    reference_images: ["https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?auto=format&fit=crop&w=600&q=80"],
    service_type: "studio_visit",
    preferred_date: "2026-09-20",
    preferred_time: "10:00",
    status: "accepted",
    estimated_price: 1400,
    deposit_amount: 250,
    deposit_paid: false,
    created_at: "2026-08-28T16:45:00Z",
    updated_at: "2026-08-29T09:30:00Z",
  },
];

// ── Mock Initial Customers ──
export const INITIAL_MOCK_CUSTOMERS: CustomerRecord[] = [
  {
    id: "cust-1",
    name: "Sophie Chen",
    email: "sophie.chen@gmail.com",
    phone: "+91 9876543210",
    city: "Vadodara",
    total_bookings: 2,
    last_booking_date: "2026-09-01",
    preferred_style: "Fine Line",
    notes: "Prefers quiet sessions with classical audio. High pain tolerance.",
    status: "active",
  },
  {
    id: "cust-2",
    name: "David Miller",
    email: "david.m@outlook.com",
    phone: "+91 9898989898",
    city: "Rajpipla",
    total_bookings: 1,
    last_booking_date: "2026-08-30",
    preferred_style: "Realism",
    notes: "Home service requested. Rajpipla residence.",
    status: "new",
  },
  {
    id: "cust-3",
    name: "Marcus Sterling",
    email: "marcus.s@sterling.co.in",
    phone: "+91 9900112233",
    city: "Surat",
    total_bookings: 4,
    last_booking_date: "2024-02-15",
    preferred_style: "Dark Realism",
    notes: "VIP Collector. Working on full right arm blackwork sleeve.",
    status: "vip",
  },
];
