import type { InspirationItem, InstagramPostItem } from "@/types";

export const INSPIRATION_CATALOG: InspirationItem[] = [
  {
    id: "insp-1",
    title: "Lord Shiva Cosmic Trishul & Damru Flow",
    description: "Devotional spiritual realism with crescent moon, sacred damru, and micro-dotwork cosmic mandala on forearm.",
    image: "/images/tattoos/shiva-trishul-tattoo.jpg",
    source: "studio",
    instagram_permalink: "https://www.instagram.com/tatoo.iconic",
    instagram_likes: "5.3k",
    instagram_comments: "215",
    style_tags: ["Spiritual", "Fine Line", "Custom"],
    primary_style: "Spiritual",
    placement: "Forearm",
    aspect_ratio: "tall",
    artist_credit: "Jainik Patel",
    is_trending: true,
  },
  {
    id: "insp-2",
    title: "Lord Hanuman Ji — Ornate Mukut & Saffron Tilak",
    description: "High-definition devotional portrait with traditional Hindi script and ornamental crown detailing.",
    image: "/images/tattoos/hanuman-tattoo.jpg",
    source: "studio",
    instagram_permalink: "https://www.instagram.com/tatoo.iconic",
    instagram_likes: "4.8k",
    instagram_comments: "162",
    style_tags: ["Spiritual", "Realism", "Script"],
    primary_style: "Spiritual",
    placement: "Forearm",
    aspect_ratio: "tall",
    artist_credit: "Jainik Patel",
    is_trending: true,
  },
  {
    id: "insp-3",
    title: "Royal Crowned Lion Dark Realism Sleeve",
    description: "Majestic photorealistic lion with volumetric fur textures and vintage imperial crown engravings.",
    image: "/images/tattoos/lion-king-tattoo.jpg",
    source: "studio",
    instagram_permalink: "https://www.instagram.com/tatoo.iconic",
    instagram_likes: "3.9k",
    instagram_comments: "128",
    style_tags: ["Realism", "Blackwork"],
    primary_style: "Realism",
    placement: "Bicep",
    aspect_ratio: "portrait",
    artist_credit: "Jainik Patel",
    is_trending: true,
  },
  {
    id: "insp-4",
    title: "Sacred Lotus Mandala & Micro-Geometry",
    description: "Ultra-crisp geometric symmetry and delicate blooming lotus petals crafted with single-needle precision.",
    image: "/images/tattoos/lotus-mandala-tattoo.jpg",
    source: "studio",
    instagram_permalink: "https://www.instagram.com/tatoo.iconic",
    instagram_likes: "4.1k",
    instagram_comments: "145",
    style_tags: ["Fine Line", "Minimalist", "Geometric"],
    primary_style: "Fine Line",
    placement: "Shoulder",
    aspect_ratio: "tall",
    artist_credit: "Jainik Patel",
    is_trending: true,
  },
  {
    id: "insp-5",
    title: "Lord Ganesha Devotional Line Art & Modak",
    description: "Devotional minimalist line art of Lord Ganesha with holy saffron tilak, modak flourish, and auspicious blessing mudra.",
    image: "/images/tattoos/ganesha-tattoo.jpg",
    source: "studio",
    instagram_permalink: "https://www.instagram.com/tatoo.iconic",
    instagram_likes: "5.1k",
    instagram_comments: "210",
    style_tags: ["Spiritual", "Fine Line", "Minimalist"],
    primary_style: "Spiritual",
    placement: "Forearm",
    aspect_ratio: "tall",
    artist_credit: "Jainik Patel",
    is_trending: true,
  },
  {
    id: "insp-6",
    title: "Chhatrapati Shivaji Maharaj Imperial Portrait",
    description: "Detailed historical realism tribute featuring the Great Maratha King with royal turban (pagadi) and sharp mustache.",
    image: "/images/tattoos/shivaji-maharaj-tattoo.jpg",
    source: "studio",
    instagram_permalink: "https://www.instagram.com/tatoo.iconic",
    instagram_likes: "6.7k",
    instagram_comments: "389",
    style_tags: ["Realism", "Spiritual", "Custom"],
    primary_style: "Realism",
    placement: "Bicep",
    aspect_ratio: "portrait",
    artist_credit: "Jainik Patel",
    is_trending: true,
  },
  {
    id: "insp-7",
    title: "Radha Krishna Divine Flute & Morpankh",
    description: "Fine-line devotional tattoo featuring Lord Krishna's sacred Bansuri flute with peacock feather and Om mandala.",
    image: "/images/tattoos/radha-krishna-tattoo.jpg",
    source: "studio",
    instagram_permalink: "https://www.instagram.com/tatoo.iconic",
    instagram_likes: "4.9k",
    instagram_comments: "174",
    style_tags: ["Spiritual", "Fine Line", "Custom"],
    primary_style: "Spiritual",
    placement: "Forearm",
    aspect_ratio: "tall",
    artist_credit: "Jainik Patel",
    is_trending: true,
  },
  {
    id: "insp-8",
    title: "Lord Shiva Trishul with Rudraksha Mala & Damru",
    description: "Spiritual realism featuring sacred Lord Shiva Trishul wrapped in textured Rudraksha bead mala necklace.",
    image: "/images/tattoos/rudraksha-trishul-tattoo.jpg",
    source: "studio",
    instagram_permalink: "https://www.instagram.com/tatoo.iconic",
    instagram_likes: "5.8k",
    instagram_comments: "260",
    style_tags: ["Spiritual", "Realism", "Custom"],
    primary_style: "Spiritual",
    placement: "Forearm",
    aspect_ratio: "tall",
    artist_credit: "Jainik Patel",
    is_trending: true,
  },
  {
    id: "insp-9",
    title: "Vintage Pocket Watch, Broken Glass & Dark Rose Realism",
    description: "Intricate vintage Roman numeral pocket watch with broken glass dial effect and velvety dark rose petals.",
    image: "/images/tattoos/rose-clock-tattoo.jpg",
    source: "studio",
    instagram_permalink: "https://www.instagram.com/tatoo.iconic",
    instagram_likes: "4.3k",
    instagram_comments: "155",
    style_tags: ["Realism", "Blackwork"],
    primary_style: "Realism",
    placement: "Arm Sleeve",
    aspect_ratio: "portrait",
    artist_credit: "Jainik Patel",
    is_trending: true,
  },
  {
    id: "insp-10",
    title: "Lord Buddha Meditative Nirvana & Sacred Lotus",
    description: "Serene meditative Lord Buddha face portrait in soft smoky black and grey shading with blooming sacred lotus blossom.",
    image: "/images/tattoos/buddha-nirvana-tattoo.jpg",
    source: "studio",
    instagram_permalink: "https://www.instagram.com/tatoo.iconic",
    instagram_likes: "4.6k",
    instagram_comments: "192",
    style_tags: ["Realism", "Spiritual", "Fine Line"],
    primary_style: "Spiritual",
    placement: "Forearm",
    aspect_ratio: "tall",
    artist_credit: "Jainik Patel",
    is_trending: true,
  },
  {
    id: "insp-11",
    title: "Dark Realism Cobra Serpent & Blooming Peonies",
    description: "High-contrast illustrative blackwork serpent coiled gracefully through large blossoming botanical peony flowers.",
    image: "/images/tattoos/serpent-peony-tattoo.jpg",
    source: "studio",
    instagram_permalink: "https://www.instagram.com/tatoo.iconic",
    instagram_likes: "3.8k",
    instagram_comments: "119",
    style_tags: ["Blackwork", "Realism", "Botanical"],
    primary_style: "Blackwork",
    placement: "Forearm",
    aspect_ratio: "tall",
    artist_credit: "Jainik Patel",
    is_trending: true,
  },
  {
    id: "insp-12",
    title: "Maa Devotional Calligraphy, Heartbeat & Lotus",
    description: "Sacred Sanskrit calligraphy honoring Mother with single-needle ECG heartbeat line and blooming lotus.",
    image: "/images/tattoos/maa-calligraphy-tattoo.jpg",
    source: "studio",
    instagram_permalink: "https://www.instagram.com/tatoo.iconic",
    instagram_likes: "6.3k",
    instagram_comments: "340",
    style_tags: ["Script", "Spiritual", "Fine Line"],
    primary_style: "Fine Line",
    placement: "Wrist",
    aspect_ratio: "tall",
    artist_credit: "Jainik Patel",
    is_trending: true,
  },
  {
    id: "insp-13",
    title: "Geometric Wolf & Howling Moon Forest Realism",
    description: "Geometric polygon wolf head seamlessly transitioning into realistic howling wolf portrait against full moon and pine trees.",
    image: "/images/tattoos/wolf-forest-tattoo.jpg",
    source: "studio",
    instagram_permalink: "https://www.instagram.com/tatoo.iconic",
    instagram_likes: "4.2k",
    instagram_comments: "138",
    style_tags: ["Geometric", "Realism", "Blackwork"],
    primary_style: "Geometric",
    placement: "Forearm",
    aspect_ratio: "tall",
    artist_credit: "Jainik Patel",
    is_trending: true,
  },
  {
    id: "insp-14",
    title: "Fine-Line Wild Botanical Peony & Ferns",
    description: "Single-needle delicate floral bouquet with micro-shading wrapping naturally around the spine.",
    image: "https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?auto=format&fit=crop&w=800&q=80",
    source: "pinterest",
    source_url: "https://pinterest.com/pin/tattoo-inspiration-fine-line",
    style_tags: ["Fine Line", "Botanical", "Minimalist"],
    primary_style: "Fine Line",
    placement: "Spine",
    aspect_ratio: "tall",
    is_trending: true,
  },
  {
    id: "insp-15",
    title: "Sacred Geometry Mandala & Metatron's Cube",
    description: "Intricate multi-layered sacred geometry with concentric circles and dotwork gradient fill.",
    image: "https://images.unsplash.com/photo-1568515045052-f9a854d70bfd?auto=format&fit=crop&w=800&q=80",
    source: "pinterest",
    source_url: "https://pinterest.com/pin/sacred-geometry-tattoo",
    style_tags: ["Minimalist", "Geometric", "Blackwork"],
    primary_style: "Minimalist",
    placement: "Chest",
    aspect_ratio: "square",
    is_trending: true,
  },
  {
    id: "insp-16",
    title: "Anatomical Heart & Wild Blooming Roses",
    description: "Fine line cardiovascular illustration intertwined with blooming organic petals and high ink contrast.",
    image: "https://images.unsplash.com/photo-1542385151-efd9000785a0?auto=format&fit=crop&w=800&q=80",
    source: "pinterest",
    style_tags: ["Fine Line", "Custom", "Botanical"],
    primary_style: "Fine Line",
    placement: "Thigh",
    aspect_ratio: "tall",
  },
];

export const INSTAGRAM_SYNCED_POSTS: InstagramPostItem[] = [
  {
    id: "ig-post-1",
    media_url: "/images/tattoos/hanuman-tattoo.jpg",
    caption: "Lord Hanuman Ji Spiritual Realism with Sacred Saffron Tilak & Bold Calligraphy. Meticulous 6-hour master session at Bhadam private suite. #TattooIconic #JainikPatel #HanumanTattoo #GujaratTattoo",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2024-03-12T14:30:00Z",
    like_count: 4820,
    comments_count: 164,
    style_tag: "Spiritual",
    placement: "Forearm",
  },
  {
    id: "ig-post-2",
    media_url: "/images/tattoos/shiva-trishul-tattoo.jpg",
    caption: "Lord Shiva Cosmic Trishul & Sacred Damru. Micro-stipple shading and sacred mandala geometric harmony on forearm. #MahadevTattoo #ShivaTrishul #FineLineTattoo",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2024-02-28T11:15:00Z",
    like_count: 5310,
    comments_count: 215,
    style_tag: "Spiritual",
    placement: "Forearm",
  },
  {
    id: "ig-post-3",
    media_url: "/images/tattoos/lion-king-tattoo.jpg",
    caption: "Royal Lion & Imperial Crown Dark Realism Bicep Piece. High contrast velvety blacks with single-needle fur highlights. #DarkRealism #LionTattoo #TattooMaster",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2024-02-10T16:45:00Z",
    like_count: 3950,
    comments_count: 128,
    style_tag: "Realism",
    placement: "Bicep",
  },
  {
    id: "ig-post-4",
    media_url: "/images/tattoos/lotus-mandala-tattoo.jpg",
    caption: "Delicate Sacred Lotus Mandala on shoulder blade. Clean single-needle symmetry that heals razor-sharp. #LotusTattoo #MandalaArt #FineLineGujarat",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2024-01-20T09:20:00Z",
    like_count: 4120,
    comments_count: 145,
    style_tag: "Fine Line",
    placement: "Shoulder",
  },
  {
    id: "ig-post-5",
    media_url: "/images/tattoos/ganesha-tattoo.jpg",
    caption: "Shree Ganesha Devotional Fine Line Art with sacred saffron tilak and modak flourish. Done with single needle precision. #GaneshaTattoo #SpiritualTattoo #Rajpipla",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2024-01-12T10:00:00Z",
    like_count: 5120,
    comments_count: 210,
    style_tag: "Spiritual",
    placement: "Forearm",
  },
  {
    id: "ig-post-6",
    media_url: "/images/tattoos/shivaji-maharaj-tattoo.jpg",
    caption: "Chhatrapati Shivaji Maharaj Imperial Portrait. 8.5 hour detailed realism session honoring the great warrior king. #ShivajiMaharaj #MarathaEmpire #RealismTattoo",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2023-12-28T16:20:00Z",
    like_count: 6740,
    comments_count: 389,
    style_tag: "Realism",
    placement: "Bicep",
  },
  {
    id: "ig-post-7",
    media_url: "/images/tattoos/radha-krishna-tattoo.jpg",
    caption: "Radha Krishna Divine Bansuri Flute with Peacock Feather & sacred Om linework. Pure devotional vibration. #RadhaKrishna #FluteTattoo #FineLineGujarat",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2023-12-15T12:45:00Z",
    like_count: 4920,
    comments_count: 174,
    style_tag: "Spiritual",
    placement: "Forearm",
  },
  {
    id: "ig-post-8",
    media_url: "/images/tattoos/rudraksha-trishul-tattoo.jpg",
    caption: "Lord Shiva Sacred Trishul wrapped with authentic Rudraksha mala beads and Damru. Dedicated to Har Har Mahadev. #Mahadev #RudrakshaTattoo #ShivaTrishul",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2023-11-25T14:10:00Z",
    like_count: 5820,
    comments_count: 260,
    style_tag: "Spiritual",
    placement: "Forearm",
  },
  {
    id: "ig-post-9",
    media_url: "/images/tattoos/rose-clock-tattoo.jpg",
    caption: "Vintage Pocket Watch with broken glass dial effect and velvety dark realism rose petals. Time waits for no one. #RoseTattoo #ClockTattoo #DarkRealism",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2023-11-08T15:30:00Z",
    like_count: 4310,
    comments_count: 155,
    style_tag: "Realism",
    placement: "Forearm / Sleeve",
  },
  {
    id: "ig-post-10",
    media_url: "/images/tattoos/buddha-nirvana-tattoo.jpg",
    caption: "Serene Lord Buddha Meditative Nirvana Portrait with blooming Sacred Lotus and Bodhi tree leaves. #BuddhaTattoo #LotusTattoo #PeacefulInking",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2023-10-22T11:00:00Z",
    like_count: 4620,
    comments_count: 192,
    style_tag: "Spiritual",
    placement: "Forearm",
  },
  {
    id: "ig-post-11",
    media_url: "/images/tattoos/serpent-peony-tattoo.jpg",
    caption: "Illustrative Blackwork Cobra Serpent entwined with lush botanical peonies. High contrast stipple dotwork. #SerpentTattoo #SnakePeony #BlackworkGujarat",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2023-10-05T13:40:00Z",
    like_count: 3840,
    comments_count: 119,
    style_tag: "Blackwork",
    placement: "Forearm",
  },
  {
    id: "ig-post-12",
    media_url: "/images/tattoos/maa-calligraphy-tattoo.jpg",
    caption: "Maa Sanskrit Calligraphy with ECG Heartbeat & Blooming Lotus. Dedicated to unconditional motherly love. #MaaTattoo #CalligraphyTattoo #FineLine",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2023-09-18T16:15:00Z",
    like_count: 6350,
    comments_count: 340,
    style_tag: "Fine Line",
    placement: "Wrist",
  },
  {
    id: "ig-post-13",
    media_url: "/images/tattoos/wolf-forest-tattoo.jpg",
    caption: "Geometric polygon wolf head seamlessly transitioning into howling wolf & moonlit pine forest. #WolfTattoo #GeometricTattoo #ForestTattoo",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2023-09-02T14:50:00Z",
    like_count: 4210,
    comments_count: 138,
    style_tag: "Geometric",
    placement: "Forearm",
  },
  {
    id: "ig-post-14",
    media_url: "https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?auto=format&fit=crop&w=800&q=80",
    caption: "Behind the scenes: Exclusive private studio session at Bhadam, Rajpipla suite. Hospital-grade sterility and zero rush. #TattooStudio #Rajpipla #Narmada",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2023-08-15T13:00:00Z",
    like_count: 2890,
    comments_count: 76,
    style_tag: "Studio",
    placement: "Studio Suite",
  },
  {
    id: "ig-post-15",
    media_url: "https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?auto=format&fit=crop&w=800&q=80",
    caption: "Luxury Home Service session in Vadodara. Bringing a hospital-sterile mobile studio directly to client's residence. #HomeTattooService #MobileInking #Gujarat",
    media_type: "IMAGE",
    permalink: "https://www.instagram.com/tatoo.iconic",
    timestamp: "2023-07-20T15:40:00Z",
    like_count: 3450,
    comments_count: 110,
    style_tag: "Home Service",
    placement: "Mobile Session",
  },
];
